name: BpCreative
favicon: null
layout_spectrum: 0.0478
typography_spectrum: 0.69651
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#1a45b6'
    - '#8a838a'
    - '#9cb2d9'
    - '#be510c'
  brandStrength: 0.8809111365117133
  lightness: 0.9257059257943183
  saturation: 0.7027085390873253
  rhythmicContrast: 0.8951778670307249
purpose: []
